spring.application.name=banking

spring.datasource.url=jdbc:mysql://localhost:3307/banking_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=${JWT_SECRET}

spring.redis.host=localhost
spring.redis.port=6379

resilience4j.circuitbreaker.instances.fraudCheck.sliding-window-size=10
resilience4j.circuitbreaker.instances.fraudCheck.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.fraudCheck.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.fraudCheck.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.fraudCheck.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.fraudCheck.automatic-transition-from-open-to-half-open-enabled=true